micronaut:
  serde:
    serialization:
      inclusion: ALWAYS
  application:
    name: oda-history-service
  security:
    authentication: bearer
    token:
      bearer:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  caches:
    jwks:
      expire-after-write: 240h
  executors:
    history-command-listener:
      type: fixed
      nThreads: 1
endpoints:
  all:
    enabled: true
    sensitive: false
  caches:
    enabled: true
  loggers:
    write-sensitive: false
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: 'history'
      default-schema: 'history'
