name: Release

on:
  push:
    branches: ["master"]

permissions: write-all

jobs:
  build-and-deploy:
    uses: "OpenDonationAssistant/oda-libraries/.github/workflows/release_service.yml@master"
    secrets: inherit
    with:
      service: history-service
      version: "${{ github.RUN_NUMBER }}"
